# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Simoleon - StoreKit Test")
  end

  desc "Upload to Testflight"
  lane :beta do
    # Get the version number from the project and check against
    # the latest build already available on TestFlight, then
    # increase the build number by 1. If no build is available
    # for that version, then start at 1
    increment_build_number(
      build_number: latest_testflight_build_number(
        initial_build_number: 1,
        version: get_version_number(xcodeproj: "Simoleon.xcodeproj")
      ) + 1,
    )

    # Set up Distribution code signing and build the app
    match(type: "appstore")
    gym(scheme: "Simoleon")

    # Upload the binary to TestFlight and automatically publish
    # to the configured beta testing group
    app_store_connect_api_key
    upload_to_testflight
  end

end
