# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
	"iPhone 8 Plus",
	"iPhone 12 Pro Max",
	"iPad Pro (12.9-inch) (4th generation)"
])

languages([
	"en-US",
	"es-ES",
	"en-GB",
	"de-DE",
	"fr-FR",
	"pt-PT",
	"nl-NL",
	"it-IT",
	"ru-RU"
])

# The name of the scheme which contains the UI Tests
scheme("Screenshots")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# Enabling this option will configure the Simulator's system language
localize_simulator(true)

# For more information about all available options run
# fastlane action snapshot
