# A list of devices you want to take the screenshots from
devices([
	"iPhone 8 Plus",
	"iPhone 12 Pro Max",
	"iPad Pro (12.9-inch) (5th generation)",
	"iPad Pro (12.9-inch) (3rd generation)"
])

languages([
	"en-US",
	"es-ES",
	"en-GB",
	"de-DE",
	"fr-FR",
	"pt-PT",
	"nl-NL",
	"it",
	"ru"
])

# The name of the scheme which contains the UI Tests.
scheme("Screenshots")

# Enabling this option will automatically uninstall the application before running it.
reinstall_app(true)

# Should the project be cleaned before building it?
clean(true)

# Enabling this option will configure the Simulator's system language.
localize_simulator(true)

# Clear all previously generated screenshots before creating new ones.
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception.
override_status_bar(true)

# For more information about all available options run
# fastlane action snapshot
